version: "3"

services:
  bitcask-server:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: bitcask-server
    # image: fb5812bbfc65
    volumes:
      - data:/data
    ports:
      - 8080:8080

volumes:
  data:
